# Generated by Django 4.2.7 on 2025-12-03 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('sector', models.CharField(choices=[('tecnologia', 'Tecnología'), ('agricultura', 'Agricultura'), ('manufactura', 'Manufactura'), ('servicios', 'Servicios'), ('comercio', 'Comercio'), ('construccion', 'Construcción'), ('educacion', 'Educación'), ('salud', 'Salud'), ('transporte', 'Transporte'), ('turismo', 'Turismo')], max_length=50, verbose_name='Sector')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('sector', models.CharField(choices=[('tecnologia', 'Tecnología'), ('agricultura', 'Agricultura'), ('manufactura', 'Manufactura'), ('servicios', 'Servicios'), ('comercio', 'Comercio'), ('construccion', 'Construcción'), ('educacion', 'Educación'), ('salud', 'Salud'), ('transporte', 'Transporte'), ('turismo', 'Turismo')], max_length=50, verbose_name='Sector')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='cooperatives', to='organizations.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooperativa',
                'verbose_name_plural': 'Cooperativas',
                'ordering': ['-created_at'],
            },
        ),
    ]
