# Generated by Django 4.2.7 on 2025-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_code',
            field=models.CharField(default='123456', help_text='Código para que otros usuarios se unan a tu empresa', max_length=20, verbose_name='Código de Acceso'),
        ),
    ]
